/// Canonical list of business categories for pending verification segregation.
const kBusinessCategories = [
  'House cleaning',
  'Pest control',
  'Tank cleaning',
  'Electricians',
  'Plumbers',
  'AC Repair',
  'Fridge Repair',
  'Washing Machine Repair',
  'CCTV Installation',
  'Water Purifier Repair',
  'Kitchen Appliances Repair',
  'TV Repair',
  'Phone & System Repairs',
  'Wood Works',
  'Glass Design Works',
  'Interior Designers',
  'Ceiling',
  'Tiles',
  'Painters',
  'Purohith',
  'Wedding Halls',
  'Photographers',
  'Catering',
  'Shamiyana',
  'Bridal and Groom Makeup',
  'Beauty Services',
  'Mehandi Artists',
  'Other Event Services',
  'Astrologers',
  'Packers and Movers',
  'Car Mechanic',
  'Bike Mechanic',
  'Car Drivers',
  'Car Travels',
  'Autos',
  'Welders',
  'Builders & Contractors',
  'Ambulance',
  'Diagnostic Centers',
  'Others',
];
