// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD44WsKvT-BDwfqCKskhvzzZer0TQOiZCo',
    appId: '1:7987576311:web:f6b845bfb39b1561ef82f2',
    messagingSenderId: '7987576311',
    projectId: 'skazo-7e5c3',
    authDomain: 'skazo-7e5c3.firebaseapp.com',
    databaseURL: 'https://skazo-7e5c3-default-rtdb.firebaseio.com',
    storageBucket: 'skazo-7e5c3.appspot.com',
    measurementId: 'G-7B4M5JS38K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTV9BLlrjY1_XJH_IiknQJUZK0lFs8icA',
    appId: '1:7987576311:android:167bf648f1cce868ef82f2',
    messagingSenderId: '7987576311',
    projectId: 'skazo-7e5c3',
    databaseURL: 'https://skazo-7e5c3-default-rtdb.firebaseio.com',
    storageBucket: 'skazo-7e5c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgYx_Sse1ePiTHLMkwwIf09pp9sSAI3cg',
    appId: '1:7987576311:ios:4533dad18dd22207ef82f2',
    messagingSenderId: '7987576311',
    projectId: 'skazo-7e5c3',
    databaseURL: 'https://skazo-7e5c3-default-rtdb.firebaseio.com',
    storageBucket: 'skazo-7e5c3.appspot.com',
    androidClientId:
        '7987576311-4kv6ia3nue2q8ci99691emcahfdrum7r.apps.googleusercontent.com',
    iosClientId:
        '7987576311-m3hrdkdkmadjifnnob9o20k1s5cb18gh.apps.googleusercontent.com',
    iosBundleId: 'com.alphagenn.skazo-admin',
  );
}
